config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get 'books/new', to:'books#new'
  post 'books/new', to:'books#create'
  get 'books/show/:id', to:'books#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  after_initialize :set_default_value, if: :new_record?

  private
    def set_default_value
      self.rentalHakata ||= false
      self.photo ||= "book.png"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_url
    else
      render books_new_url
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :publicationYear, :rentalHakata, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<% @books.each do |book| %>
  <%= image_tag book.photo %>
  <h3><%= link_to book.title, "books/show/#{book.id}" %></h3>
<br>
<% end %>

app/views/books/new.html.erb
<h1>新しい本</h1>
<%= form_for(@book, url: books_new_path) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br>
  <%= f.label :publicationYear %>
  <%= f.number_field :publicationYear %>
  <br>
  <%= f.label :rentalHakata %>
  <%= f.check_box :rentalHakata %>
  <br>
  <!--
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  -->

  <%= f.submit "新しい本のデータの作成" %>
<% end %>

app/views/books/show.html.erb
<%= image_tag @book.photo %>
<h3><%= @book.title %></h3>
<p><%= @book.author %> 著</p>
<p>博多オフィスにあるか: <%= @book.rentalHakata %> </p>
<!-- タグをここに表示する -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ヘッダー -->
    <header>
      <h1><%= link_to '本を読んで記録するアプリ', root_path %></h1>
      <ul>
        <li><%= link_to 'TOP', root_path %></li>
        <li><%= link_to '新しい本のデータの作成', books_new_path %></li>
        <li>本を検索</li>
        <li>ログイン</li>
        <li>新規ユーザー</li>
      </ul>
    </header>
    <!-- ヘッダー終わり -->
    <%= yield %>
  </body>
</html>